version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/redis_data
    ports:
      - target: 5000
        published: 5000
      - target: 8888
        published: 8888
    env_file:
      - devops/redis.env            
    environment:
      CONTAINER_TYPE: web
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/redis_data
    env_file:
      - devops/redis.env
    environment:
      CONTAINER_TYPE: worker
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  
  redis:
    image: redis:5.0.6-alpine
    ports:
      - target: 6379
        published: 6379
    expose:
      - 6379
